### ISSUE TITLE
Profile picture pixelating

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#199]
On some devices, the image retrieved from the Camera or Gallery is severely downscaled.

**Comment by wvictor-rr** [comment]
We need to confirm that we're saving the image to external storage properly before upload.

https://developer.android.com/training/camera/photobasics.html#TaskPath

**Comment by FredJEhlers** [comment]
I am struggling to recreate the event described above, I have added a 20mb image file and used that as the profile picture and it did not pixelate
