### ISSUE TITLE
Challenge Activity

### ISSUE THREAD

**Issue by rjacobs31** [praekeltfoundation/gem-bbb-indo#2]
- [x] Restructure in-app challenge model
- [x] Integrate with challenge fetch API
- [ ] Setup no challenges available screen
- [x] Setup handling for quiz challenges
- [ ] Setup handling for picture challenges
- [ ] Setup handling for freeform answer challenges
- [x] Setup answer submission
- [ ] Write challenge unit tests

**Comment by wvictor-rr** [comment]
Invalid because of wireframe changes and restructure.
