### ISSUE TITLE
Registration page: Spacing issue in name

### ISSUE THREAD

**Issue by LisaAdamsPRK** [praekeltfoundation/gem-bbb-indo#204]
**Issue:**
The example name has a space in it. When I entered my name and surname the validation told me that it cannot have a space. 

**Proposed Solution:**
Either change the validation to accept a space, or the example text to not include a space

Logged by: Jane
Date: 3 Dec 2016

**Comment by wvictor-rr** [comment]
Needs discussion

**Comment by rjacobs31** [comment]
Fixed in #258.
- Space in example name removed.
