### ISSUE TITLE
Registration page: Registration not completing

### ISSUE THREAD

**Issue by LisaAdamsPRK** [praekeltfoundation/gem-bbb-indo#205]
**Issue:**
After completing all fields, and hitting the register button, nothing happens. 

Logged by: Jane
Date: 3 Dec

**Comment by wvictor-rr** [comment]
@Lashes08 A possible cause is that the registration process failed (eg. network error) and the UI isn't giving good feedback.

Related to https://github.com/praekeltfoundation/gem-bbb-indo/issues/239

**Comment by wvictor-rr** [comment]
@ReinhardtCromhout Please look into using Snackbars to report server errors to the user on the onboarding screens. Have a look at how I did this on the [login screen](https://github.com/praekeltfoundation/gem-bbb-indo/blob/develop/app/src/main/java/org/gem/indo/dooit/views/onboarding/LoginActivity.java#L82)

**Comment by wvictor-rr** [comment]
@Lashes08 Better user feedback was added. Please Retest.
