### ISSUE TITLE
Coach (Conversation UI): Goal carousel not displaying

### ISSUE THREAD

**Issue by LisaAdamsPRK** [praekeltfoundation/gem-bbb-indo#209]
_Device: Xiaomi 
Device Make: Mi5 
App Version: 0.0.6 
Screen Name: 02. Setting A Goal-02
UX Flow: Setting a goal_

Issue: Cannot select predefined goal from carousel

Date: 04/12/2016
[https://drive.google.com/file/d/0BxkyIy2ixdpGVFFJcWlBQTFuaFU/view](url)

**Comment by wvictor-rr** [comment]
@Lashes08 This is probably because the predefined goals were not set up on the CMS. Please retest.
