### ISSUE TITLE
Coach (Conversation UI): Auto scroll to last message

### ISSUE THREAD

**Issue by LisaAdamsPRK** [praekeltfoundation/gem-bbb-indo#211]
_Device: Xiaomi
Device Make: Mi5
App Version: 0.0.6
Screen Name: 02. Setting A Goal-02
UX Flow: Setting a goal_

**Issue:** 
Conversational UI does not auto scroll to the last message from the coach which means you could miss some of the messages it says
**Date:** 04/12/2016

**Comment by ChristiaanSaaiman** [comment]
@Lashes08 Hi Lisa

I can't seem to recreate the experienced problem, could you retest and if it happens again, please include the steps that lead to the issue ^^ Thanks

**Comment by wvictor-rr** [comment]
Scrolling has been refined since the quick answer view layout has been changed in https://github.com/praekeltfoundation/gem-bbb-indo/pull/518
