### ISSUE TITLE
Goals (Target): Percentage text not visible below graph

### ISSUE THREAD

**Issue by LisaAdamsPRK** [praekeltfoundation/gem-bbb-indo#213]
_Device: Xiaomi
Device Make: Mi5
App Version: 0.0.6
Screen Name: 03-Tracking progress 35
UX Flow: Tracking progress_

**Issue:**
Goal percentage graph needs to gap at the bottom as per design. Cannot see percentage text.
**Date:**04/12/2016
https://drive.google.com/file/d/0BxkyIy2ixdpGLUdPcUx6WWdCeFk/view

**Comment by wvictor-rr** [comment]
@Lashes08 Do you mean the circular progress bar is covering the percentage text?

I can't seem to reproduce this. I thought it could be an Android version thing, it displays correctly on Jelly Bean 4.2. Could you confirm your device's version?

**Comment by LisaAdamsPRK** [comment]
@wvictor-rr yes indeed, I will have this retested.
