### ISSUE TITLE
Goals (Target): Goal page not displaying goal

### ISSUE THREAD

**Issue by LisaAdamsPRK** [praekeltfoundation/gem-bbb-indo#214]
_Device: Xiaomi
Device Make: Mi5
App Version: 0.0.6
Screen Name: 03-Tracking progress 35
UX Flow: Tracking progress_

**Issue:**
The details of the goal created in the conversational UI need to show in the Goal page 
**Date:**04/12/2016
https://drive.google.com/file/d/0BxkyIy2ixdpGLUdPcUx6WWdCeFk/view?usp=sharing

**Comment by ChristiaanSaaiman** [comment]
@Lashes08 Hi Lisa, please can you tell me how you got this bug? I have trouble finding a way to recreate it.

**Comment by wvictor-rr** [comment]
@ChristiaanSaaiman This could be because the image was still uploading as the user navigated to the Goals. We can either:
- Consider the Goal uploaded only when the image is also done uploading
- Persist a temporary image on the phone storage for the Goal screen to use while the upload completes
