### ISSUE TITLE
Challenges: Hint text display

### ISSUE THREAD

**Issue by LisaAdamsPRK** [praekeltfoundation/gem-bbb-indo#217]
_Device: Xiaomi
Device Make: Mi5
App Version: 0.0.6
Screen Name: 05. Quiz Challenge-04
UX Flow: Quiz Challenge_

**Issue:**
Hint text is going off the screen. Cannot catch hints.
**Date:** 4/12/2016
https://drive.google.com/file/d/0BxkyIy2ixdpGMVJVNmxBdzE5OHM/view

**Comment by wvictor-rr** [comment]
Fixed in https://github.com/praekeltfoundation/gem-bbb-indo/pull/201

Will include in 0.0.8 release.
