### ISSUE TITLE
Challenges: Quiz completion with incorrect screen

### ISSUE THREAD

**Issue by LisaAdamsPRK** [praekeltfoundation/gem-bbb-indo#218]
_Device: Xiaomi
Device Make: Mi5
App Version: 0.0.6
Screen Name: 05. Quiz Challenge-04
UX Flow: Quiz Challenge_

**Issue:**
When you have finished answering all quiz questions it takes you back to the challenge splash screen, Should be Challenge Done page.
**Date:** 4/12/2016
https://drive.google.com/file/d/0BxkyIy2ixdpGUDhxd3AwX0tFelk/view

**Comment by wvictor-rr** [comment]
Fixed in https://github.com/praekeltfoundation/gem-bbb-indo/pull/234

Will include in 0.0.8 release.
