### ISSUE TITLE
Challenge: Ts&Cs not repsonsive

### ISSUE THREAD

**Issue by LisaAdamsPRK** [praekeltfoundation/gem-bbb-indo#219]
_Device: Samsung
Device Make: Galaxy Core
App Version: 5.1.1
Screen Name: Challenge Home Page_

**Issue:**
When you click the terms and condition page,the link doesn't respond. Doesn't redirect to Terms and Condition challenge page.
**Date:** 5/12/2016
**Logged By:** Mpolokeng

**Comment by wvictor-rr** [comment]
Will be included in 0.0.8 release

**Comment by wvictor-rr** [comment]
@Lashes08  Terms & Conditions on Challenge splash screen is now clickable
