### ISSUE TITLE
Tips: Buttons placement

### ISSUE THREAD

**Issue by LisaAdamsPRK** [praekeltfoundation/gem-bbb-indo#221]
_Device: Xiaomi
Device Make: Mi5
App Version: 0.0.6
Screen Name: 06 Tips 03
UX Flow: Tips_

**Issue:**
Move next / back buttons to the bottom of the screen. Looks odd with buttons lingering in the middle of the page.
**Date:** 04/12/2016
https://drive.google.com/file/u/3/d/0BxkyIy2ixdpGQzA1ajQ1aERJYVk/view?usp=sharing

- [X] Move buttons to bottom of screen
- [x] Make buttons appear at shorter articles when article longer than viewport is present

**Comment by ChristiaanSaaiman** [comment]
I got the buttons to appear at the bottom of the screen, unfortunately this caused another bug where the buttons appear off screen on short articles if an article larger than the viewport is on the same Tip Page

- [X] Fixed
