### ISSUE TITLE
Tips: Listicle page not displaying current page

### ISSUE THREAD

**Issue by LisaAdamsPRK** [praekeltfoundation/gem-bbb-indo#222]
_Device: Xiaomi
Device Make: Mi5
App Version: 0.0.6
Screen Name: 06 Tips 03
UX Flow: Tips_

**Issue:**
Listicle page dots don't show which page one is on, they are all back, user doesn't know if they are at the beginning or end of the listicle.
**Date:** 04/12/2016
https://drive.google.com/file/d/0BxkyIy2ixdpGQzA1ajQ1aERJYVk/view

Fixes:
- [X] Make active dot yellow on tips screen.

**Comment by ChristiaanSaaiman** [comment]
Fixed #222
