### ISSUE TITLE
Tips: Incorrect placement of listicle background

### ISSUE THREAD

**Issue by LisaAdamsPRK** [praekeltfoundation/gem-bbb-indo#223]
_Device: Xiaomi
Device Make: Mi5
App Version: 0.0.6
Screen Name: 06 Tips 03
UX Flow: Tips_

**Issue:**
Listicle background pattern should go to top of page. Tip page has white bar on top which looks like a mistake (same as Terms and Conditions in Profile)
**Date:** 04/12/2016
https://drive.google.com/file/d/0BxkyIy2ixdpGQzA1ajQ1aERJYVk/view

**Comment by ChristiaanSaaiman** [comment]
@Lashes08 The background pattern does cover the entire area, the white bar at the top is actually the notification bar which contains the time, signal, battery and notifications area. Unfortunately we can't change that without completely removing the notification bar.
