### ISSUE TITLE
Tips: Listicle spacing 

### ISSUE THREAD

**Issue by LisaAdamsPRK** [praekeltfoundation/gem-bbb-indo#224]
_Device: Xiaomi
Device Make: Mi5
App Version: 0.0.6
Screen Name: 06 Tips 03
UX Flow: Tips_

**Issue:**
Listicle copy should have more line spacing. Text looks squashed and is difficult to read.
**Date:** 04/12/2016
https://drive.google.com/file/d/0BxkyIy2ixdpGQzA1ajQ1aERJYVk/view

- [x] Change line spacing to 1.5

**Comment by ChristiaanSaaiman** [comment]
Fixed #224
