### ISSUE TITLE
Tips: Search bar improvement

### ISSUE THREAD

**Issue by LisaAdamsPRK** [praekeltfoundation/gem-bbb-indo#225]
_Device: Xiaomi
Device Make: Mi5
App Version: 0.0.6
Screen Name: 06 Tips 03
UX Flow: Tips_

**Issue:**
Hide keyboard once search query has been entered. Keyboard hides most of the search results page. 
**Date:** 04/12/2016
https://drive.google.com/file/d/0BxkyIy2ixdpGUWM4TDAwdDdFZ28/view

**Comment by wvictor-rr** [comment]
Fixed in https://github.com/praekeltfoundation/gem-bbb-indo/pull/236. Please retest.
