### ISSUE TITLE
Tips: Next / Back Button improvement

### ISSUE THREAD

**Issue by LisaAdamsPRK** [praekeltfoundation/gem-bbb-indo#226]
_Device: Xiaomi
Device Make: Mi5
App Version: 0.0.6
Screen Name: 06 Tips 03
UX Flow: Tips_

**Issue:**
We need to design an active and inactive state for the next and back buttons to replace the orange outline. Buttons inconsistent with design. 
**Date:** 04/12/2016
https://drive.google.com/file/d/0BxkyIy2ixdpGMktVUnVNVXd0S3c/view

**Comment by ChristiaanSaaiman** [comment]
@Lashes08 Could you please elaborate on the issue? When you mean active and inactive state, does that mean you don't want the ability to go back to the first article on the tip page when reaching the end and pressing the "next" button and vice versa? Do we need to make the "prev" button inactive at the start of the listicle and the "next" button inactive at the end of the listicle?

Buttons inconsistent with design - What part bothers you? Would you like for us to change the colour, font or shape? ^^

Thank you for testing it thus far :)

**Comment by wvictor-rr** [comment]
@ChristiaanSaaiman New buttons have been designed. I'll forward you the email.

**Comment by ChristiaanSaaiman** [comment]
@ReinhardtCromhout I believe you handled this right?
