### ISSUE TITLE
Spannable styled strings only aligned for English

### ISSUE THREAD

**Issue by rjacobs31** [praekeltfoundation/gem-bbb-indo#247]
Spannable strings should use `TextSpannableHelper` to ensure that the styling is applied in both languages, delimited by `*` (see `ChallengeRegisterFragment.java`):
- [x] Convert onboarding registration page (`RegistrationActivity.java`).
- [x] ~Convert tips list adapter (`TipsListAdapter.java`).~ (Unnecessary)

**Comment by ChristiaanSaaiman** [comment]
The `RegistrationActivity.java` has been converted to use `TextSpannableHelper`
Unfortunately I cannot seem to get `TipListAdapter.java` to make use of the `TextSpannableHelper`

**Comment by rjacobs31** [comment]
@ChristiaanSaaiman The tips lists adapter does not seem to be a candidate for `TextSpannableHelper`. Apologies. If you have `RegistrationActivity` ready to go, you can put in a PR.

**Comment by ChristiaanSaaiman** [comment]
Fixed #247
