### ISSUE TITLE
Webview Translation

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#253]
When opening CMS content in a WebView, translations are not provided. The WebView is not sending an `Accept-Language` header.

Example is the Tips screen. The Next and Prev buttons are not translated.

**Comment by wvictor-rr** [comment]
@rjacobs Please have a look at how we can set the language header when using the WebView. If it's easy enough to accomplish, then assign it to @ChristiaanSaaiman

**Comment by rjacobs31** [comment]
@wvictor-rr As @ChristiaanSaaiman has been moved to another project, I've assigned this to @FredJEhlers. He has already found a way to set the headers, but we're unsure how to test whether the translations are taking effect.
