### ISSUE TITLE
`Add Goal` Toolbar action menu is not visible on lower API levels

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#254]
Toolbar style is not applied as expected on API level 21 and lower. The `ADD GOAL` action menu item is not visible as the text is white (same as toolbar)

**Comment by wvictor-rr** [comment]
@rjacobs @FredJEhlers please help me investigate

**Comment by FredJEhlers** [comment]
@wvictor-rr downloading Lollipop and kitkat, will inform you of what I find

**Comment by wvictor-rr** [comment]
Looks like it's fixed. Thanks!
