### ISSUE TITLE
Change Name to Username on Registration and Login

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#275]
_Language: Indonesian
Device Make: Xiaomi
Device Model: Mi5
App Version: 0.0.9
Logged by: Pippa_

Change the name field on registration to say `Username` and change the example to `Bina124`

This is the Unique identifier for the user. so we need to keep it but would prefer that it is a username (it is Name currently) and add an additional `Name` field to registration where we ask users for their first name.

**Comment by wvictor-rr** [comment]
Fixed by https://github.com/praekeltfoundation/gem-bbb-indo/pull/305

**Comment by FredJEhlers** [comment]
@wvictor-rr Bina124 was not added
Will add it now
