### ISSUE TITLE
Challenge popup

### ISSUE THREAD

**Issue by rjacobs31** [praekeltfoundation/gem-bbb-indo#278]
- [ ] Implement challenge invite popup.
- [ ] Automatically display popup when there is a _new_ challenge available.

**Comment by wvictor-rr** [comment]
When the `MainActivity` is opened, it should check from the server if a current challenge is available. If a challenge is available, it should show this lightbox popup.

Pressing *Start* should direct the user to the Challenge screen.

![challenge popup](https://cloud.githubusercontent.com/assets/22614906/22781233/45287094-eeca-11e6-84d8-f11fa87f63be.PNG)
