### ISSUE TITLE
Challenge Design

### ISSUE THREAD

**Issue by rjacobs31** [praekeltfoundation/gem-bbb-indo#30]
- [ ] ~Challenge popup (to start)~ _Moved to dedicated issue #278_ 
- [x] Register for challenge
- [x] Quiz option selection
- [x] Quiz answer correct
- [x] Quiz answer incorrect
- [x] Picture challenge capture photo
- [x] Picture challenge re-take
- [x] Freeform text challenge edit
- [x] Challenge complete
- [ ] ~Confetti~ _Moved to dedicated issue https://github.com/praekeltfoundation/gem-bbb-indo/issues/277_

**Comment by wvictor-rr** [comment]
@rjacobs31 Do you want to keep this issue open on this milestone, move it to a later milestone, or create a new issue for **"Challenge popup (to start)"**?
