### ISSUE TITLE
Add CSS styles to support all WYSIWYG options

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#302]
- [x] Bold
- [x] Italic
- [x] Header 2
- [x] Header 3
- [x] Header 4
- [x] Header 5
- [x] Ordered List
- [x] Unordered List
- [x] Horizontal rule
- [x] Hyperlink
- [x] Image

**Comment by FredJEhlers** [comment]
![css demo](https://cloud.githubusercontent.com/assets/17107161/21767855/16e0b344-d67f-11e6-9060-ed1f22f6bbe2.png)

Here is a print screen of the css would you like changes or is this fine?

**Comment by FredJEhlers** [comment]
Cellphone screenshot
![screenshot_1483969004](https://cloud.githubusercontent.com/assets/17107161/21768287/82cbe98c-d681-11e6-824b-6971bbc7dc14.png)
