### ISSUE TITLE
Implement Translations in Django

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#31]
Requires https://github.com/praekeltfoundation/gem-bbb-indo/issues/26 to start
- [x] Translate _content_ app
- [x] Translate _users_ app

**Comment by wvictor-rr** [comment]
Moved to [Release 2016-11-11](https://github.com/praekeltfoundation/gem-bbb-indo/milestone/2) on account of dependency on https://github.com/praekeltfoundation/gem-bbb-indo/issues/26

**Comment by rjacobs31** [comment]
The initial translation files have been created. More complex integration may be necessary in the future, but these should cover the admin pages. #26
