### ISSUE TITLE
Carousel: Images in predefined goals must load faster

### ISSUE THREAD

**Issue by FredJEhlers** [praekeltfoundation/gem-bbb-indo#399]
Carousel images need to load faster. Investigate how to load Predefined Goal carousel images before the conversation starts. The loading images are confusing the users.

Remember to change signal settings in the emulator to use `Poor signal` and `Edge connection` in order to test this bug. Clear app data and cache

Look into `Fresco` library about fetching before hand however if a "pre fetch" was executed by the time you get to the carousel another request is made regardless, so prevent the second request

**Comment by wvictor-rr** [comment]
http://frescolib.org/docs/caching.html
