### ISSUE TITLE
Layout issue: correct the Recycler view so the end of scrolling page work as expected

### ISSUE THREAD

**Issue by FredJEhlers** [praekeltfoundation/gem-bbb-indo#412]
Chat bubble appears below the "you've reached the bottom of this chat" animation on android.
a link for visual representation of the issue: [Demo](https://drive.google.com/open?id=0By-6VifH6WAOMDhiZ2tkZlRSV2M)

Happens on many of the fragments, It has to do with where the `Recycler View' ends and others begin. This will affect many aspects needs exploration on how to implement, low priority

**Comment by wvictor-rr** [comment]
This has been fixed when the quick answer layout changed
