### ISSUE TITLE
BOT: HashtagView has a few errors

### ISSUE THREAD

**Issue by FredJEhlers** [praekeltfoundation/gem-bbb-indo#414]
The Hashtag View is what the bot uses to provide options for the user to choose from to progress through the conversations. Here are the issues with it: 

- If the message is long and requires two lines to display it, the message is truncated and can become unclear as what it will enable the user to do

- Ordering of the options that the user can choose from is not consistent between languages (I assume it is ordered according to text length I am not sure) 

- In a set of options we want a different options to be able to have different background colours (eg a red delete option among the other blue options)

It might be required to fork the Hashtag View repository and modify it to allow our changes to be a possibility.

- [x] Messages are no longer being truncated 
- [x] Ordering of the options are consistent between languages 
- [x] Different options can have different colours

**Comment by wvictor-rr** [comment]
We should investigate using a `RecyclerView` with a staggered layout.
