### ISSUE TITLE
Knowledge Quiz

### ISSUE THREAD

**Issue by FredJEhlers** [praekeltfoundation/gem-bbb-indo#418]
Knowledge Test (Quiz duplicate feature) to be developed as separated from Quiz Challenges and to be delivered to a user on a specific time frame from when they first registered on the app

Want to test user's knowledge at certain points in their user journey 

ON HOLD until scope is defined

**Comment by wvictor-rr** [comment]
This is not related to surveys. Knowledge quizzes are their own feature.
