### ISSUE TITLE
Reporting exports from command line

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#476]
Reporting needs to be reviewed to ensure that pertinent data is being collected as expected.

Example reports need to be created that resemble the requirements outlined by the SOW as closely as possible, using data from the QA server.

Create `manage.py` commands that will export the appropriate reports.

## Reports

- **User count, Goal reached** - Number of users who have received a goal reached badge 
- **User count, Goal modified** - Number of users who choose edit savings amount and select change amount or change date.
- **User count, Badges** - Number of users who have received a badge
- **User count, Quiz Challenge** - Number of users who have completed a quiz challenge
- **User count, weekly target streak** - Number of users who input savings weekly
- **User count, weekly savings streak** - Number of users who input savings weekly
- **User count, at least one Goal created** - Number of users with at least one goal set

**Comment by ChadGarrett** [comment]
Possible django extension to implement reporting: [django-repport-builder](http://django-report-builder.readthedocs.io/en/latest/quickstart/)
