### ISSUE TITLE
Unable to share Badges using Facebook or Twitter

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#483]
Users attempted to share Badges via `ProfileActivity`, but Facebook and Twitter were not included in the chooser drawer.

It's possible the Facebook and Twitter apps were not installed on the device.

If the appropriate apps were installed on the device, and we can't reproduce the issue, then we will need to log sharing information to Crashlytics.

1 hour investigation

**Comment by ChadGarrett** [comment]
Tested on API 22 and 25. Sharing to Facebook and Twitter only shows when they are installed, otherwise it defaults to sharing as a text message if no other sharing apps are available. 

Trying to get Twitter and Facebook installed on API 17 to test further.
