### ISSUE TITLE
Survey: Change consent question

### ISSUE THREAD

**Issue by FredJEhlers** [praekeltfoundation/gem-bbb-indo#504]
Split out the question "If you are 17 years of age or younger: Does a parent or guardian agree to you completing this survey?" to " Are you "17 years or younger?" (Yes/No) and if yes, " Does a parent consent to you completing this survey"

**Comment by wvictor-rr** [comment]
When is consent considered to be given? There are now two paths to consenting to the survey.

### Case 1:

- 17 years or younger? -> **Yes**
- Does a parent consent to you completing this survey -> **Yes** (start survey)

Consent is **True**

### Case 2:

- 17 years or younger? -> **Yes**
- Does a parent consent to you completing this survey -> **No** (cancel survey)

Consent is **False**

### Case 3:

- 17 years or younger? -> **No** (start survey)
- Does a parent consent to you completing this survey -> **N/A**

Consent is **True**
