### ISSUE TITLE
Add Challenge title to winning Badge

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#507]
The winning Badge needs a special layout where the Challenge's title is included in the Badge's card layout, while the image is still the Badge's image.

![winning badge](https://cloud.githubusercontent.com/assets/22614906/22414356/7db96b6c-e6c7-11e6-9780-735903d0f6a5.PNG)

30 minutes frontend
30 minutes backend

**Comment by FredJEhlers** [comment]
With regards to the inconsistent first bot message i went with the one specified in the #506
