### ISSUE TITLE
fragment_target_savings_plan not displaying correct values

### ISSUE THREAD

**Issue by ReinhardtCromhout** [praekeltfoundation/gem-bbb-indo#517]
The fragment_target_savings_plan message displays incorrect values for the weekly target when viewing a Goal in the Target Screen

**Comment by ReinhardtCromhout** [comment]
This is due to the fact that server is storing/sending incorrect values to the app

**Comment by ReinhardtCromhout** [comment]
The issue is occurring due to the fact that the start and end dates are handled differently in the app and on the server. In particular this means that what is defined as "a week" differs on the server and on the app which means the "week count" differs, we need a more clear definition on what die client wants defined as "one week"

**Comment by wvictor-rr** [comment]
Moved to [GEMINDO-154](https://praekeltorg.atlassian.net/browse/GEMINDO-154)
