### ISSUE TITLE
Persisted.java line 360

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#530]
#### in org.gem.indo.dooit.helpers.Persisted.getUserUUID

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/retro-rabbit/android/apps/org.gem.indo.dooit.staging/issues/589489460aeb16625bdaa815](https://fabric.io/retro-rabbit/android/apps/org.gem.indo.dooit.staging/issues/589489460aeb16625bdaa815)

**Comment by ReinhardtCromhout** [comment]
I am fairly certain this was cause on my device, an error I made when testing the google analitics on my branch

**Comment by wvictor-rr** [comment]
No problem
